Update orders.yml
18F/ads-bpa pull request #79
Opened 2018-07-03 20:16 UTC by rrefoy

Moved several projects from awarded to delivered, updated status of 4th FS buy.

2018-07-03 21:06 UTC, lauraGgit commented
the build is failing - trying to figure what is up

2018-07-16 16:54 UTC, lauraGgit requested changes

2018-07-16 16:54 UTC, lauraGgit commented on data/orders.yml
> +  solicitation_date: TBD
this TBD breaks the sort because it is looking for a date, so I suggest we either put something or remove it.

2018-07-16 18:00 UTC, rrefoy commented
I think i fixed it

2018-07-16 18:23 UTC, lauraGgit approved these changes

2018-07-16 18:23 UTC, merged